version: "3"
services:
  postgres:
    image: "postgres:16-alpine"
    container_name: theinterview-infrastructure-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:?}
    networks:
      - common

  redis:
    image: "redis:7.2.1-alpine"
    container_name: theinterview-infrastructure-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis/d–∞ta:/root/redis
      - ./data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    env_file: .env
    networks:
      - common

networks:
  common:
    driver: bridge
